root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/server"
  cmd = "mage generate && go build -ldflags='-s -w' -o ./tmp/server ./cmd/web"
  pre_cmd = []
  delay = 1000
  exclude_dir = ["bin", "tmp", "vendor", "testdata", "docs", ".git"]
  exclude_file = ["magefile.go"]
  exclude_regex = ["_test\\.go$", ".*_templ\\.go$", ".*\\.sql\\.go$", "mage_.*\\.go$", "internal/store/db\\.go$", "internal/store/models\\.go$", "internal/store/queries\\.sql\\.go$"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "sql"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true