version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.24"



linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
    - goconst
    - gocritic
  disable:
    - cyclop
    - funlen
    - gocognit
    - nestif
    - lll
    - wsl
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    gocritic:
      disabled-checks:
        - exitAfterDefer
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - path: internal/store/queries.sql.go
        linters:
          - revive
      - path: internal/ui/embed.go
        linters:
          - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0