version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.24"

output:
  text:
    colors: true
    print-issued-lines: true
    print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
    - goconst
    - gocritic
  disable:
    - cyclop
    - funlen
    - gocognit
    - nestif
    - lll
    - wsl

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  gocritic:
    disabled-checks:
      - exitAfterDefer

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: internal/store/queries.sql.go
      linters:
        - revive
    - path: internal/ui/embed.go
      linters:
        - staticcheck
  max-issues-per-linter: 0
  max-same-issues: 0