services:
  postgres:
    image: postgres:16-alpine
    container_name: gowebserver-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gowebserver
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gowebserver"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: