// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string             `db:"token" json:"token"`
	Data   []byte             `db:"data" json:"data"`
	Expiry pgtype.Timestamptz `db:"expiry" json:"expiry"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Name         string             `db:"name" json:"name"`
	AvatarUrl    *string            `db:"avatar_url" json:"avatar_url"`
	Bio          *string            `db:"bio" json:"bio"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	IsActive     *bool              `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
