name: CI Pipeline

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Install SQLite
      run: sudo apt-get update && sudo apt-get install -y sqlite3

    - name: Setup development tools
      run: mage setup

    - name: Run CI pipeline
      run: mage ci

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin/
        retention-days: 30

    - name: Check binary sizes
      run: |
        echo "📦 Binary Sizes:"
        ls -lh bin/
        echo ""
        echo "🎯 Total Size:"
        du -sh bin/