name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24'

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Run Setup
      run: mage setup

    - name: Generate Code
      run: mage generate

    - name: Run Vet and VulnCheck
      run: mage vet && mage vulncheck
      
    - name: Run Lint
      run: mage lint

    - name: Run Build
      run: mage build
